### ISSUE TITLE
Illegal syntax in type extensions with generics does not throw syntax error

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1611]
The following compiles, but I don't think it should:

```
type X<'T> = Y of 'T
type X<'T when 'T :> string> with
    static member X = 2
    static member take (s: 'T) = s
```

The following uses generic syntax that isn't allowed anywhere else where generic syntax is allowed:

```
type X<'T> when 'T :> string with
    static member X = 2
    static member take (s: 'T) = s
```

And even if it should compile, and accept the restriction, it should then raise an error because `string` is sealed.

First raised as [StackOverflow question here](http://stackoverflow.com/questions/40011958/type-extensions-with-a-generic-constraint-not-raising-an-error-nor-doing-what-m), the answer seems to agree with me (in that it shouldn't compile).

**Comment by cloudRoutine** [comment]
There are a lot of oddities related to the generics syntax - #1494

**Comment by abelbraaksma** [comment]
That's indeed quite odd as well. Though this is different, in that 1) #1494 refers to statically resolved type params, this is "just" a normal constraint 2) this one is specific for a  type _extension_, and 3) the 2nd example above is very illegal (I think) as it "escapes" the `<...>` boundaries of the generic syntax.

**Comment by dsyme** [comment]
Thanks.  The constraints for type augmentations are implied by the constraints at the type definition. Adding explicit new constraints at the augmentation should give an error or warning.

**Comment by abelbraaksma** [comment]
> Adding explicit new constraints at the augmentation should give an error or warning.
Agreed. Add to that that illegal syntax on the augmentation (see 2nd example) should surely raise a syntax error and not just a warning or be ignored.

**Comment by forki** [comment]
type X<'T> = Y of 'T
    type X<'T when 'T :> string> with
        static member X = 2
        static member take (s: 'T) = s

is interesting.

![image](https://cloud.githubusercontent.com/assets/57396/20627070/f62c3468-b31d-11e6-96e0-14151237defb.png)

but if I compile separately:

![image](https://cloud.githubusercontent.com/assets/57396/20627088/23df6c2c-b31e-11e6-83ad-df62803e2af6.png)

@dsyme any ideas why this is different?

**Comment by 0x53A** [comment]
AFAIK a type extension is merged into the original type, if both are in the same compilation unit (similar to partial classes in C#) and implemented as extension methods, if in different CUs (e.g. in different Assemblies).

**Comment by dsyme** [comment]
@forki @0x53A That is correct, it changes from an intrinsic extension to an extrinsic extension.

**Comment by abelbraaksma** [comment]
@KevinRansom, @dsyme, this is only partially fixed. The OP shows two examples, but in VS2017 with either F# 4.0 or F# 4.1 I can see that the first example now raises the error mentioned in @forki's comment above, but the second example is truly invalid syntax and the compiler does not notice it.

From above:
```
// should give a syntax error, but raises an error FS0698 on the string-constraint
type X<'T> = Y of 'T
type X<'T> when 'T :> string with
    static member X = 2
    static member take (s: 'T) = s
```

This variant compiles but shouldn't, it is clearly a syntax error (the `when` constraint is not within the `<` and `>`)

    type X<'T> when 'T :> obj = Y of 'T
