### ISSUE TITLE
[<RequireQualifiedAccess>] on a DU shadows types in the same module

### ISSUE THREAD

**Issue by Tarmil** [Microsoft/visualfsharp#1253]
I think this issue is an unfortunate consequence of the way #95 was fixed. Consider the following code:

``` fsharp
module A =
    [<RequireQualifiedAccess>]
    type U = | C

    type C() =
        static member M() = ()
```

Since `U` has `RequireQualifiedAccess`, using `A.C` should unambiguously refer to the class rather than the union case. But as it stands, when I call `A.C.M()`, the compiler thinks `A.C` refers to `A.U.C` and fails with the following:

```
warning FS0035: This construct is deprecated: The union type for union case 'C' was defined with the RequireQualifiedAccessAttribute. Include the name of the union type ('U') in the name you are using.

  A.C.M();;
  ----^

error FS0039: The field, constructor or member 'M' is not defined
```

**Comment by ant0nsc** [comment]
Submitted as #1294

**Comment by forki** [comment]
proposed a fix in #1512

**Comment by forki** [comment]
after looking into this I don't think it's introduced with #95 - it looks like this has been there longer and #95 just introduced one warning more.

**Comment by liboz** [comment]
@forki This bug seems to have been around at least since F# 2.0.

**Comment by forki** [comment]
yeah. I was a bit shocked when I read that I was resposible. Happy that I don't get the blame this time ;-)

**Comment by Tarmil** [comment]
Yeah sorry for making it seem like #95 introduced this, it is of course not the case. The reason I mentioned it in the report is that this error is actually consistent with the buggy semantics from before that fix. This is basically a subset of bug #95.

**Comment by dsyme** [comment]
Fixed https://github.com/Microsoft/visualfsharp/pull/1512

**Comment by forki** [comment]
can this be merged to FCS?

**Comment by dsyme** [comment]
@forki All changes will eventually be merged into FCS. We just need to integrate visualfsharp --> fsharp --> FCS....

**Comment by dsyme** [comment]
@forki BTW I think we're getting closer to being able to build FCS nuget from this repo.  No we're seeing more momentum in the VS IDE tools it might be time to start doing that.  We would need to brings Expres.fs into here, plus arrange CI testing on Linux and Windows (about half is already in place)
