### ISSUE TITLE
Getting ref to static mutable field is an error in F# 4.5

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#5420]
Referencing a class static mutable field via &amp; stopped compiling in F# 4.5.  Example:

type MyClass () =
    [&lt;DefaultValue&gt;]
    static val mutable private nextInstanceIndex : int
    static do
        MyClass.nextInstanceIndex &lt;- 1
    let instanceIndex = System.Threading.Interlocked.Increment(&amp;MyClass.nextInstanceIndex) - 1

Compilation results in error FS3236: Cannot take the address of the value returned from the expression. Assign the returned value to a let-bound value before taking the address.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/301281/getting-ref-to-static-mutable-field-is-an-error-in.html
VSTS ticketId: 655347_
_These are the original issue comments:_

James Horvath on 7/27/2018, 08:32 AM (3 days ago): <p>Here's that code formatted:</p><pre>type MyClass () =
	[&lt;DefaultValue&gt;]
	static val mutable private nextInstanceIndex : int
	static do
		MyClass.nextInstanceIndex &lt;- 1
	let instanceIndex = System.Threading.Interlocked.Increment(&MyClass.nextInstanceIndex) - 1
<br></pre>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Interestingly, this code does not run in F# Interactive with F# 4.1 today:

```
Microsoft (R) F# Interactive version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 

~vs33E9.fsx(6,64): error FS0257: Invalid mutation of a constant expression. Consider copying the expression to a mutable local, e.g. 'let mutable x = ...'.

> 
```

And the IDE in 15.7.5 is not okay with it either:

<img width="723" alt="screen shot 2018-07-30 at 10 48 43" src="https://user-images.githubusercontent.com/6309070/43413908-2dbdd3d2-93e6-11e8-94d9-03207e0bebaf.png">

**Comment by cartermp** [comment]
This also fails to compile with F# 4.0 in [repl.it](https://repl.it/@cartermp/GlisteningBoilingQuagga).

@jhorv do you have another code sample that could demonstrate a break with F# 4.5?

**Comment by cartermp** [comment]
I think that if it worked in Preview 4, that may be due a bug in the compiler that was fixed in our last round of cleanup around Span/ref/pointer work that only landed in Preview 5. That's just a hunch, but considering it didn't work in the last released compiler and continues to not work in the current one, I don't think we'll consider this a bug.

@Tihan do you have any thoughts on this? It is interesting to note that error messages are now different with this code.

**Comment by TIHan** [comment]
Looking at this right now.

**Comment by TIHan** [comment]
This is most likely not a bug; but a possible improvement.

The reason why it was compiling in Preview 4 is because we started out allowing devs to take the address of expressions. We disallowed it again in Preview 5.

This code, `&MyClass.nextInstanceIndex` fails because in fact it is trying to take the address of an expression (internally when I look at the AST). But it does look like it's trying to take the address of a field; which is why this looks confusing. 

The error message, before and after, also do not describe what's happening very well and how to fix the error properly considering what you intended to do.

I don't know the details of why it is this way, but my hunch it may have to do with initialization. I did find some interesting info here: http://www.ianvoyce.com/index.php/2010/10/01/public-static-fields-gone-from-f-2-0/

An alternative is this:
```fsharp
type MyClass () =
    static let mutable nextInstanceIndex = 1
    let instanceIndex = System.Threading.Interlocked.Increment(&nextInstanceIndex) - 1
```
That compiles and should give the same desired effect; with less code too.
