### PR TITLE
More whitespace normalization

### PR DESCRIPTION
**Pull request by dsyme**
The F# compiler code generally uses "space for application when the argument is an atomic expression", e.g.

* `Some xyz`
* `someFunction abc`
* `someFunction abc.P`
* `someFunction abc.[1]`
* `C.SomeMethod abc`
* `obj.SomeMethod abc.P`
* `SomeUnion.CaseA xyz`
* `member x.SomeMethod abc = ...`
* `static member SomeMethod abc = ...`

Also it uses space after application unless fluent notation is explcitly being used (the use of fluent notation is fairly rare in the # codebase), so
* `TOp.Foo (arg1, arg2)`  

and so on. The above does not apply to `new C(arg)` nor `type C(arg) = ...` where parens must be used.

However the codebase is riddled with inconsistencies, e.g. all of the below can be seen:
* `Some xyz`
* `Some(xyz)`
* `Some (xyz)`

This PR removes many of these inconsistencies making the codebase closer to the style first listed, which is already the majority of code.

### CODE REVIEW

**Comment by auduchinok** [comment]
Why is the `c.Method 123` is preferred over `c.Method(123)`? It makes two perceived different syntaxes used depending on a method taking a single argument or many.
We've discussed it before and I'm still in favor of having spaces used for curried functions application and parents for methods.

I really like all the previous whitespace cleanup but this change looks a bit controversial to me.

**Comment by dsyme** [comment]
> I'm working on the dev16.0 merge into master, can you hold off on this until that is done?

Yes you get that in first, then I'll update this.

If you want me to help with the merge let me know, especially if conflicts have been due to this cleanup.

**Comment by dsyme** [comment]
> Why is the c.Method 123 is preferred over c.Method(123)? It makes two perceived different syntaxes used depending on a method taking a single argument or many.

I understand the position, especially for using .NET library methods.  It's a fine discussion for Fantomas default settings and the style guide.  

However what we need here is consistency rather than the mishmash we have.   For the purposes of code cleanup, this is how most of the compiler is already written, and we're not going to add a whole lot of `(`..`)` to code that doesn't have it.  So this is just how it is and we need to be consistent.

As we make this codebase more consistent, we will get to the point that formatting the compiler with Fantomas will be a no-op (because it is consistent), and we can literally just switch the settings universally across the codebase.  We're a long way from that but consistency is crucial.

**Comment by dsyme** [comment]
The FSC compiler from the .NET SDK using the bootstrap is hitting a bug on Linux and macOS as of commit #97d7a02: 
```
    13>FSC : error FS2014: A problem occurred writing the binary '/Users/vsts/agent/2.149.2/work/1/s/fcs/../artifacts/obj/fcs/net461/FSharp.Compiler.Service.dll': EmitZUntaggedIndex: too big for small address or simple index [/Users/vsts/agent/2.149.2/work/1/s/fcs/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
```
his bug has cropped up now and then.  The current compiler code has some extra instrumentation for this error to help us diagnose it, but compiling using the exact commit above might help us understand it too

**Comment by dsyme** [comment]
@brettfo This is ready to go in after your dev16.0 integration lands in master

**Comment by brettfo** [comment]
Thanks for holding off on this.  `master` is in a good state so you can do whatever you need now.

**Comment by dsyme** [comment]
@KevinRansom @TIHan This is ready, review please? thanks

**Comment by dsyme** [comment]
@TIHan If there are other particular inconsistencies you'd like me to chase down please let me know (there are probably quite a few candidates!)
