### PR TITLE
Allow the creation of portable pdb files on Mono

### PR DESCRIPTION
**Pull request by nosami**
Allows the generation of .pdb files on Mono when `--debug:portable` is specified
on the command line. `--debug:full` continues to  generate .mdb files as
before. 

Previously, `.mdb` files would be produced on mono regardless of the command line switch.

### CODE REVIEW

**Comment by nosami** [comment]
Application debugging with full mono desktop runtime / portable pdb.
screen shot 2017-04-05 at 18 08 16

Debugging on coreclr / portable pdb
screen shot 2017-04-05 at 18 07 51

**Comment by KevinRansom** [comment]
@nosami Thanks, for this.

**Comment by dsyme** [comment]
Compilation error:
```
  D:\j\workspace\release_ci_pa---c6929ad7\src\absil\ilwritepdb.fs(201,5): error FS0034: Module 'Microsoft.FSharp.Compiler.AbstractIL.ILPdbWriter' contains    val internal getDebugFileName<'a> : outfile:string -> portablePDB:'a -> string    but its signature specifies    val internal getDebugFileName : string -> bool -> string    The respective type parameter counts differ [D:\j\workspace\release_ci_pa---c6929ad7\src\fsharp\FSharp.Compiler\FSharp.Compiler.fsproj]
```

**Comment by dsyme** [comment]
@nosami You should type annotate ``portablePDB`` with ``(portablePDB:bool)``

**Comment by dsyme** [comment]
@nosami I added the annotation directly to your branch

**Comment by nosami** [comment]
@dsyme: Oops, thanks!

**Comment by dsyme** [comment]
@KevinRansom Status is this:

* We have a bootstrap build in this repo (Ubuntu 14.04) but no real testing.  
* fsharp/fsharp adds some testing (a subset of fsharp/fsharp) and more mono variations.

**Comment by nosami** [comment]
@dsyme @KevinRansom : I would really like to get some fsharp/fsharp testing done internally against all mono branches (HEAD of mono branch / HEAD of fsharp). I can spend some time looking into this soon.

**Comment by dsyme** [comment]
> @dsyme @KevinRansom : I would really like to get some fsharp/fsharp testing done internally against all mono branches (HEAD of mono branch / HEAD of fsharp). I can spend some time looking into this soon.

That would be really great.
