### ISSUE TITLE
DbmlFile type provider not working with VS2017 15.7

### ISSUE THREAD

**Issue by mjmckp** [Microsoft/visualfsharp#4856]
[test.zip](https://github.com/Microsoft/visualfsharp/files/1982900/test.zip)

The attached project just contains a single instance of the `Microsoft.FSharp.Data.TypeProviders.DbmlFile` type.

It does not compile with 15.7, but does with prior versions.  The compile error is:

`FSC: error FS0193: Could not find file 'C:\temp\test\tmp357A.dll'.`

Which I presume is some kind of temporary file generated by the type provider?

**Comment by cartermp** [comment]
Closing as duplicate of https://github.com/Microsoft/visualfsharp/issues/4795

This has been fixed and is pending a servicing fix
