### ISSUE TITLE
Cannot compile FSharp.Core with dotnet core 2.1

### ISSUE THREAD

**Issue by ncave** [Microsoft/visualfsharp#5311]
Should I be able to? Works fine with dotnet core 2.0:
- 2.1.201 and below - works.
- 2.1.300 and above - does not work.

Here is the error:

```FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'string'```

If that helps, the error is easily reproducible in other .fsproj if you add: `<OtherFlags>--compiling-fslib</OtherFlags>`

**Comment by TIHan** [comment]
I'm not able to reproduce the issue unless I add that flag; it even happens on .NET Core 2.0. Also, you should never use that flag for a real project so I'm not surprised things would break.

**Comment by TIHan** [comment]
You are trying to compile FSharp.Core as a .NET Core library?

**Comment by ncave** [comment]
@TIHan Absolutely, netstandard2.0 to be precise.

**Comment by cartermp** [comment]
I don't expect that to work, since it is build against `netstandard1.6`. We'll eventually move off of that and make it a `netstandard2.0` component, but I'm afraid that isn't in immediate plans, as it will require a major rev of the package that may have to coincide with F# 5.0.

**Comment by TIHan** [comment]
I see. At some point, we will want to ship FSharp.Core as a netstandard 2.0 lib; which we will run into the issue you described. I'll make note of it so we can revisit it.

**Comment by ncave** [comment]
I don't think you can compile it to netstandard1.6 either with .NET Core 2.1.301 (but 2.1.201 works fine).

**Comment by ncave** [comment]
The good news is .NET Core 2.1.400 preview seems to work fine, so I guess it's just the 2.1.30x that has the issue.

**Comment by cartermp** [comment]
I can't say if I've tried it, but I wonder if `project.json` is even supported with a .NET Core SDK build for .NET Core 2.1.

**Comment by ncave** [comment]
@cartermp That's not it, you can take it out but same thing. It's something to do perhaps with compiler switches, as it breaks very early, right away.

**Comment by ncave** [comment]
This appears to have been fixed since then, works now. Thanks!

**Comment by cartermp** [comment]
No worries! Thanks for looping back here.
