### PR TITLE
Warn/Error when a Custom Attribute does not derive from Attribute

### PR DESCRIPTION
**Pull request by KevinRansom**
@vasily-kirichenko provide this PR: https://github.com/Microsoft/visualfsharp/pull/5192

Which makes CustomAttributes which do not derive from System.Attribute an error.

Our requirements are:
1. It must be be a warning for existing projects, which developers will see and choose to fix.  
2. An error in all new projects .NET FRamework and .NET Sdk.
3. An Error for existing .NET Sdk projects.

**Justification,**
It's a breaking change and has been usable for ever on .NET Framework projects, it is however, bad practice and can cause common .Net attribute reflection idioms to not work correctly.

So on .NET framework, we want to issue a warning because the existing behavior is wrong, and developers have the opportunity to fix it.

On .NET Sdk projects, we feel that the projects were recent and still highly likely to be actively developed.  This will require developers to correct the attribute definition and move on …

Kevin

### CODE REVIEW

File: src/fsharp/FSComp.txt [hunk 1]
```diff
@@ -1435,8 +1435,9 @@ notAFunctionButMaybeDeclaration,"This value is not a function and cannot be appl
 3230,chkNoWriteToLimitedSpan,"This value can't be assigned because the target '%s' may refer to non-stack-local memory, while the expression being assigned is assessed to potentially refer to stack-local memory. This is to help prevent pointers to stack-bound memory escaping their scope."
 3231,tastValueMustBeLocal,"A value defined in a module must be mutable in order to take its address, e.g. 'let mutable x = ...'"
 3232,tcIsReadOnlyNotStruct,"A type annotated with IsReadOnly must also be a struct. Consider adding the [<Struct>] attribute to the type."
-3233,chkStructsMayNotReturnAddressesOfContents,"Struct members cannot return the address of fields of the struct by reference"
```
Comment (KevinRansom) [inline src/fsharp/FSComp.txt]: Hmm, I think these numbers should be returned to their original value.  I have no idea how this happened I guess it was some merge nonsense.

Comment (KevinRansom) [reply src/fsharp/FSComp.txt]: Yes I should, otherwise this basically undoes this change:  https://github.com/Microsoft/visualfsharp/commit/d97c7976ccbd0a2605fcb9db055ead82b8049598
