### ISSUE TITLE
Can't compile WindowsApplication (instead of ConsoleApplication)

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3008]
If I set the Output type to Windows Application 
![image](https://cloud.githubusercontent.com/assets/4236651/25846751/566c152a-34b3-11e7-86bd-f49d6f79797d.png)
![image](https://cloud.githubusercontent.com/assets/4236651/25846761/5f723852-34b3-11e7-86e4-a82ccc92a5c9.png)

then it will pass the autogenerated AssemblyAttributes.fs as the last file, breaking the entry point:

```
3>------ Build started: Project: TIM-Update, Configuration: Debug x64 ------
3>	C:\dev\p4\2017PrecastTim\TimPrecast\packages\FSharp.Compiler.Tools\build\..\tools\fsc.exe -o:C:\dev\p4\2017PrecastTim\TimPrecast\Sources\..\BuildTemp\Debug\TIM-Update\x64\Debug\TIM-Update.exe
3>-g
3>--debug:full
3>--noframework
3>--define:DEBUG
3>--define:TRACE
3>--doc:C:\dev\p4\2017PrecastTim\TimPrecast\Sources\..\BuildOutput\x64\DebugTIM-Update.XML
3>--optimize-
3>--tailcalls-
3>--platform:x64
...
3>AssemblyInfo.fs
3>Program.fs
3>C:\Users\lrieger\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.fs
3>
3Program.fs(224,5): error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence.
3>Done building project "TIM-Update.fsproj" -- FAILED.
3>
3>Build FAILED.
========== Build: 2 succeeded, 1 failed, 12 up-to-date, 0 skipped ==========
```

If I revert that change and go back to ConsoleApp, it correctly passes it as the first item.

```
3>C:\Users\lrieger\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.fs
3>AssemblyInfo.fs
3>Program.fs
```

Restarting VS didn't help.

**Comment by 0x53A** [comment]
Not that this does NOT occur when I create a new F# project, so I don't have a repro yet. (Can't share my work solution).

**Comment by dsyme** [comment]
@0x53A I believe this is fixed on master, see https://github.com/Microsoft/visualfsharp/blame/9c7563470ebfdf752d65695850216dc3f854cf1a/src/fsharp/FSharp.Build/Microsoft.FSharp.targets#L322

For workaround either edit the Microsoft.FSharp.targets file you're using to explicitly have the above fix

**Comment by 0x53A** [comment]
Yup, the issue was with FSharp.Compiler.Tools, after updating from 4.1.5 to 4.1.17, it now seems to work.
Thanks.
