### ISSUE TITLE
Potential FSC issue with .NET 4.7.2

### ISSUE THREAD

**Issue by psantoro** [Microsoft/visualfsharp#5964]
I'm using .NET 4.7.2 and Visual Studio 2017 Developer Command Prompt v15.9.2.  When I use FSI and enter the following, it appears to work fine:

let hset = System.Collections.Generic.HashSet<string>(100, HashIdentity.Structural);;

However, if I try to compile a file with using the same .NET 4.7.2 HashSet constructor via FSC, I get compile errors similar to the following:

hashset.fs(11,60): error FS0001: The type 'int' is not compatible with the type 'IEnumerable<string>'

hashset.fs(11,60): error FS0193: Type constraint mismatch. The type
    'int'
is not compatible with type
    'IEnumerable<string>'

#### Repro steps

Provide the steps required to reproduce the problem

1. Open Visual Studio 2017 Developer Command Prompt v15.9.2 on system with .NET 4.7.2 installed.

2. Use FSC to compile file using the new .NET 4.7.2 HashSet constructor noted above (see attached sample file).

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

I expect the F# command line tools to support the latest installed .NET version.

#### Actual behavior

It appears that .NET 4.7.2 is not supported by FSC.  I'm guessing this is related to issue #4946.

#### Known workarounds

None.

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Operating system - Windows 7 Enterprise, Windows 10 Professional
* Branch
* .NET Runtime, CoreCLR or Mono Version - .NET 4.7.2
* Editing Tools (e.g. Visual Studio Version) - Vim
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity
[hashset.zip](https://github.com/Microsoft/visualfsharp/files/2627099/hashset.zip)

**Comment by cartermp** [comment]
Yes, this is ultimately caused by #4946. I'll close as a duplicate of that.
