### ISSUE TITLE
Type Inference broken recently.

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#1296]
Existing code I have no longer compiles.

#### Repro steps

    open System.Text
    open System.Runtime.CompilerServices
    open System.Runtime.InteropServices

    [<Extension; Sealed>]
    type T = 
        [<Extension>]static member Append (x:StringBuilder, y:StringBuilder) = StringBuilder().Append(x).Append(y)

#### Expected behavior

Compiles fine.

#### Actual behavior

No longer compiles:

          [<Extension>]static member Append (x:StringBuilder, y:StringBuilder) = StringBuilder().Append(x).Append(y);;
      ---------------------------------------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    stdin(16,83): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

#### Related information 

I'm not sure exactly where it stopped working, but I can tell you for sure It worked on ba3fee7652c02512872e6e80f4d7c6b6767b15f8 and it doesn't work in 4e562f339ea4578c0ca6c9b784f2aa8f092079ac.

**Comment by forki** [comment]
trying to find bad commit in #1296

**Comment by forki** [comment]
OMG 4e562f3 is huge.

**Comment by dsyme** [comment]
I'm in two minds about whether this should be considered a breaking change (which needs to be reverted) or a fix.

Basically, the question is whether extension members are in scope within their own implementations. 

* If so, the code above should give an error, as ``StringBuilder().Append(x)`` gets resolved to a recursive use of the extension member itself, and the return type is unknown, hence the error on subsequent lookup.

* If not, the code above should not give an error, as ``StringBuilder().Append(x)``  gets resolved to the ``StringBuilder.Append(obj)`` overload!

The PR for the "mutrec" changed the behaviour.

Morally speaking it is the "right" thing to put the extension members in scope. Certainly in the ``namespace rec`` case, where such things are essentially order-independent. But for the sake of compatibility I suppose we should not apply the rule in the non-rec case.

I'll prepare a fix

**Comment by gmpl** [comment]
After your explanation it makes sense to me the new behaviour. If you ask me I'm happy if you leave it as it is from now, especially considering that it's a very rarely used pattern and at the same time very easy workaround it.

**Comment by dsyme** [comment]
@gmpl I'm concerned that this will be (slightly) more common than we think. I'll look into it further.  I don't like changing the behavior of existing code in such ways, partly because it is relatively hard for people to understand the change

**Comment by dsyme** [comment]
@gmpl I've thought about this and agree we should resolve it as by design

I'm quite surprised we actually found this early though - are you running a lot of code through the latest master bits?

**Comment by gmpl** [comment]
@dsyme Yes, I'm linking [FSharpPlus](https://github.com/gmpl/FSharpPlus) in almost all my projects and code snippets, which use a lot of unique F# features like overloads with member constraints and minimal type annotations.
I can tell you that each time I try to modify something in the F# compiler my code breaks immediately though still pass all tests in the F# compiler.
Specifically this "bug" (or feature) I found it while compiling [FsControl](https://github.com/gmpl/FsControl) but already [fixed the code] (https://github.com/gmpl/FsControl/commit/8213cae15aeaffc76a3807575ca77be921928fc1) and works fine now.

**Comment by dsyme** [comment]
@gmpl If you'd like to contribute a snapshot version of FSharpPlus as a test case that would be hugely appreciated.  And indeed any other OSS F# libraries.  At least we would then know if we're breaking things relatively early

**Comment by gmpl** [comment]
@dsyme Sure, I think that's a good idea, we need more "corner case" tests, specially for the constraint solver. Will look forward into it.
