### ISSUE TITLE
FS0438 DuplicateMethod does not respect CompiledNameAttribute

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#5711]
### Repro steps

The below code does not compile in F#4.5 and gives the following error:

`
error FS0438: Duplicate method. The method 'Create' has the same name and signature as another method in type 'Thing' once tuples, functions, units of measure and/or provided types are erased.
`

```fsharp
open FSharp.Core
open FSharp.Data.UnitSystems.SI.UnitSymbols

type Thing =
    | Thing of int
    | Other of int<kg>
    static member Create x = Thing x
    static member Create x = Other x
```

This makes perfect sense - at compile time, we can know which of the two overloads to call, but at runtime there would be no way to distinguish them.

However, rewriting the type as follows still leads to the same compiler error:

```fsharp
type Thing =
    | Thing of int
    | Other of int<kg>
    static member Create x = Thing x
    [<CompiledName "CreateKg">]
    static member Create x = Other x
```

To confirm that the `CompiledName` attribute indeed works, if you rename the second `Create()` member to e.g. `CreateSecond()` and reflect over this type this is what you will get:

```fsharp
let names = typeof<Thing>.GetMethods() |> Array.map(fun m -> m.Name)

val names : string [] =
  [|"NewThing"; "get_IsThing"; "NewOther"; "get_IsOther"; "get_Tag";
    "ToString"; "CompareTo"; "CompareTo"; "CompareTo"; "GetHashCode";
    "GetHashCode"; "Equals"; "Create"; "CreateKg"; "Equals"; "Equals";
    "GetType"|]
```

Notice that `CreateSecond` is correctly renamed to `CreateKg`.

Why does the compiler complain here - is there something else that affects the overload resolution at runtime etc.?

**Comment by zpodlovics** [comment]
I guess this check probably happens at measure generic erasure time before the CompiledName evaluated [1].

[1] https://github.com/Microsoft/visualfsharp/blob/46b758f1142011029d5cd61959c64bf6e3acdb66/src/fsharp/PostInferenceChecks.fs#L1906

**Comment by dsyme** [comment]
Yes, this is by design

**Comment by isaacabraham** [comment]
@dsyme by design as in, "we never did this" or "we specifically don't want to support this in the future"? Is there any reason, from an end-user point of view, why this wouldn't be desirable - and is my assessment that it *could* be possible to support this one day valid?

**Comment by cartermp** [comment]
I personally don't think we should get in the business of attributes being accounted for in overload resolution, and I expect @dsyme would agree with this. `CompiledName` is primarily for interop with the rest of .NET, not an alternative syntax for the names of things in source. If it could affect overload resolution, it would be reasonable to expect to be able to use it in the same file with the `CompiledName` representation:

```fsharp
open FSharp.Data.UnitSystems.SI.UnitSymbols

type Thing =
    | Thing of int
    | Other of int<kg>
    static member Create x = Thing x
    [<CompiledName "CreateKg">]
    static member Create' x = Other x
    
Thing.Create 12 |> ignore
Thing.CreateKg 12 |> ignore
```

But this obviously doesn't work. If we did, then we'd be creating an alternative system for referring to names in source code, which I think is not a reasonable thing to do.

**Comment by isaacabraham** [comment]
@cartermp hmmm. I see where you're coming from, but I'm not sure I agree: The error in this case *specifically refers* to runtime type erasure; it's not a compile-time issue in terms of overload resolution, but a runtime one. I wouldn't expect to be able to call `CreateKg` at compile time, but I *would* expect at runtime to be able to reflect over the type and see that name.
