### ISSUE TITLE
F# solution doesn't build correctly

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4741]
Since upgrading to 15.3, one of our F# solution claims the following:

Error		
One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'xxx'	xxx.xxxx.xxxxx	X:\xxx\xxx\xxx.fs

This builds fine in 2015, and the previous version of 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/98962/f-solution-doesnt-build-correctly.html
VSTS ticketId: 483572_
_These are the original issue comments:_

Phillip Carter [MSFT] on 8/23/2017, 01:29 PM (238 days ago): <p>Hello Mo,</p><p><br></p><p>Thanks for reporting this.  This sounds like a change in the compiler for F# 4.1 that is affecting you.  However, we can't do much with this information right now.  Is there a smaller reproduction you could provide?  Thanks!</p>
Phillip Carter [MSFT] on 8/24/2017, 11:43 AM (237 days ago): <p>Tagging as Needs more Info for our system.</p>

Mo Jiwa on 8/29/2017, 02:57 AM (232 days ago): <pre><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/11427-library1.zip">library1.zip</a>

The following code builds correctly in VS2015, but fails in VS2017 with the error: Error FS0957 One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'RowSelection&lt;_&gt;' FailingLibrary xxx\FailingLibrary\FailingLibrary\Library1.fs 68 Active

The "Code" button doesn't appear to be working correctly in my browser, so I've also attached the .fs file

namespace FailingLibrary

open System.Collections.Generic

type RowSelection&lt;'TItem&gt; when 'TItem : comparison (collection) =
   let lastSelectedItem = ref None
   let selectedItem = ref None
   let selectedItems = HashSet&lt;'TItem&gt;()
    
   let add item = selectedItems.Add(item) |&gt; ignore
   let remove item = selectedItems.Remove(item) |&gt; ignore

   let selectItem (item:'TItem) =
      selectedItem :=
         if selectedItems.Contains(item) 
         then remove item; None
         else add item; Some item

   let shiftSelect toItem =
       match !lastSelectedItem with
       | Some fromItem -&gt;
          let xs = collection |&gt; Seq.toArray
          match xs |&gt; Seq.tryFindIndex ((=) fromItem ) with
          | Some a -&gt;
             match !selectedItem with
             | Some item -&gt; 
                match xs |&gt; Seq.tryFindIndex ((=) item) with
                | Some b -&gt;
                  let a,b = if a &lt;= b then a,b else b,a
                  let removeItems = [|for i = a to b do yield xs.[i]|]
                  for item in removeItems do remove item
                | None -&gt; ()
             | None -&gt; ()
             let b = xs |&gt; Seq.findIndex ((=) toItem )
             let a, b = if a &lt;= b then a, b else b, a
             let addItems = [|for i = a to b do yield xs.[i]|]
             for item in addItems do add item
             selectedItem := Some toItem
          | None -&gt; selectItem toItem
       | None -&gt; selectItem toItem

   let select(item, isShift, isControl) =
      if isShift then
         shiftSelect item
      elif isControl then
         selectItem item
         lastSelectedItem := !selectedItem
      else 
         selectedItems.Clear()
         selectItem item
         lastSelectedItem := !selectedItem

   member this.Select(item,isShift,isControl) = select(item,isShift,isControl)
   member this.SelectIndex(index,isShift,isControl) =
      if index &gt;= 0 && index &lt; Seq.length collection then
         let item = collection |&gt; Seq.item index
         select(item, isShift, isControl)
   member this.Contains(item) = selectedItems.Contains(item)
   member this.Items = selectedItems
   member this.SelectedItem = !selectedItem
   member this.SelectedIndex = 
      match !selectedItem with
      | Some item -&gt; collection |&gt; Seq.tryFindIndex ((=) item)
      | None -&gt; None

open System.Windows.Input

type RowSelection with
    member selection.SelectItem(item) =
       let isDown x = Keyboard.Modifiers.HasFlag(x)
       selection.Select(item, isDown ModifierKeys.Shift, isDown ModifierKeys.Control)
    member selection.SelectIndex(index) =
       let isDown x = Keyboard.Modifiers.HasFlag(x)
       selection.SelectIndex(index, isDown ModifierKeys.Shift, isDown ModifierKeys.Control)

<br></pre>

Phillip Carter [MSFT] on 8/29/2017, 02:46 PM (231 days ago): <p>Hey Mo,</p><p><br></p><p>I was able to get this to compile in a Library project with 15.3.3 + the F# Nightly release.  This release has a few bug fixes that may be relevant here.  These were my steps:</p><p><br></p><ol><li>Create new project.</li><li>Add assembly references to WindowsBase and PresentationCore.</li><li>Paste the code you attached.</li><li>Build.</li></ol><p>I did note that there is a warning on the type extension (type parameters have a missing or wrong type constraint that does not match the original type constrints), but that didn't seem to matter here.</p><p><br></p><p>You can install the nightly releases by following the instructions here: https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/</p><p><br></p><p>They're quite stable, but if you're leery about using them in production, they're easy to uninstall.  But if you could verify that you don't see a build failure anymore with them, that would be great!</p>
Mo Jiwa on 8/30/2017, 00:16 AM (231 days ago): <p>Hi Phillip, </p><p>I have updated to 15.3.3 and installed the F# tools Nightly release, but to no avail. </p><p>I still get the same error on that file, and others in the solution that had the same issue before. <br>I also have this error:</p><p><br>The "ResolvePackageFileConflicts" task failed unexpectedly.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at Microsoft.NET.Build.Tasks.ItemUtilities.GetTargetPath(ITaskItem item)
   at Microsoft.NET.Build.Tasks.ItemUtilities.GetReferenceTargetPath(ITaskItem item)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.&lt;&gt;c.&lt;ExecuteCore&gt;b__35_1(ConflictItem ci)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.ResolveConflicts(IEnumerable`1 conflictItems, Func`2 getItemKey, Action`1 foundConflict, Boolean commitWinner, Action`1 unresolvedConflict)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()</p><p>But I believe that is something that has already been raised:</p><p>https://developercommunity.visualstudio.com/content/problem/98225/the-resolvepackagefileconflicts-task-failed-unexpe.html</p><p>and</p><p>https://github.com/dotnet/sdk/issues/1538</p>

_These are the original issue solutions:_
(no solutions)
